name: Sysdig Scan

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Download Dockerfiles
      run: |
        wget -O voteDockerfile https://github.com/dockersamples/example-voting-app/blob/main/vote/Dockerfile
        wget -O vorkerDockerfile https://github.com/dockersamples/example-voting-app/blob/main/worker/Dockerfile
        wget -O resultDockerfile https://github.com/dockersamples/example-voting-app/blob/main/result/Dockerfile
    - name: Download sysdig-cli-scanner
      run: |
        curl -sSL https://download.sysdig.com/stable/sysdig-cli-scanner > /usr/local/bin/sysdig-cli-scanner
        chmod +x /usr/local/bin/sysdig-cli-scanner
    - name: Build images
      run: |
        docker build -t dockersamples/examplevotingapp_vote . -f voteDockerfile
        docker build -t dockersamples/examplevotingapp_worker . -f vorkerDockerfile
        docker build -t dockersamples/examplevotingapp_result . -f resultDockerfile

   
