name: Sysdig Scan

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout original repository
      uses: actions/checkout@v3
      with:
        repository: dockersamples/example-voting-app  # Replace with the actual repository details
        path: original-repo  # Clone into a subdirectory to avoid conflicts
    - name: Download sysdig-cli-scanner
      run: |
        curl -LO "https://download.sysdig.com/scanning/bin/sysdig-cli-scanner/$(curl -L -s https://download.sysdig.com/scanning/sysdig-cli-scanner/latest_version.txt)/linux/amd64/sysdig-cli-scanner" 
        sudo chmod +x sysdig-cli-scanner
    - name: Build images
      run: |
        cd original-repo/vote
        docker build -t dockersamples/examplevotingapp_vote . -f Dockerfile
        cd ../worker
        docker build -t dockersamples/examplevotingapp_worker . -f Dockerfile
        cd ../result
        docker build -t dockersamples/examplevotingapp_result . -f Dockerfile
    - name: Scan Vote
      continue-on-error: true
      env:
        SECURE_API_TOKEN: ${{ secrets.SECURE_API_TOKEN }} 
      run: |
        SECURE_API_TOKEN=$SECURE_API_TOKEN ./sysdig-cli-scanner --apiurl https://app.us4.sysdig.com dockersamples/examplevotingapp_vote
    - name: Scan Worker
      continue-on-error: true
      env:
        SECURE_API_TOKEN: ${{ secrets.SECURE_API_TOKEN }} 
      run: |
        SECURE_API_TOKEN=$SECURE_API_TOKEN ./sysdig-cli-scanner --apiurl https://app.us4.sysdig.com dockersamples/examplevotingapp_worker
    - name: Scan Result
      continue-on-error: true
      env:
        SECURE_API_TOKEN: ${{ secrets.SECURE_API_TOKEN }} 
      run: |
        SECURE_API_TOKEN=$SECURE_API_TOKEN ./sysdig-cli-scanner --apiurl https://app.us4.sysdig.comdockersamples/examplevotingapp_result


