name: Sysdig Scan

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Download Dockerfiles
      run: |
        wget https://github.com/dockersamples/example-voting-app/blob/main/vote/Dockerfile
        wget https://github.com/dockersamples/example-voting-app/blob/main/worker/Dockerfile
        wget https://github.com/dockersamples/example-voting-app/blob/main/result/Dockerfile
